# === Basic configuration ===

site:
  # Your sites's name
  appname: "testblog"

  # Blog title
  title: 'A Test Blog'

  # Author name
  author: 'John Doe'
  
  # Avatar filename/URL
  avatar: 'gravatar'

    # Hero image/URL
  hero: "something.png"

  copyright: " "

social:
    github: "PerlDancer"
    twitter: "PerlDancer"
    linkedin: none
    facebook: none
    instagram: none

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer2 will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# === Engines ===

template: "template_toolkit"
engines:
    template:
        template_toolkit:
            # Note: start_tag and end_tag are regexes
            #start_tag: '[%'
            #end_tag:   '%]'
            start_tag: '{{'
            end_tag:   '}}'

