# === Basic configuration ===
site:
    # Your sites's name
    appname: "testblog"

    # Blog title
    title: 'A Test Blog'

    appname: "cromedome.blog"
    title: 'cromedome.blog - the ramblings of Jason A. Crome'
    paginate: 5
    copyright: "Copyright &copy; Jason A. Crome 2001-2021"
    license: ""
    comment_count: true
    gdpr: false

author:
    # Avatar filename/URL, or gravatar
    avatar: 'gravatar'

    # Hero image URL
    hero: ""

    # Biographical info
    name: 'John Doe'
    bio: "Someone of remarkable character"
    location: "Smallville, Your State, USA"

    social:
        github: "PerlDancer"
        twitter: "PerlDancer"
        linkedin: none
        facebook: none
        instagram: none

# === Widget configuration ===
widgets:
    disqus:
        shortname: test

# === Waltz/Dancer specific - don't change unless you know what you're doing! ===
# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer2 will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# Engine config
template: "template_toolkit"
engines:
    template:
        template_toolkit:
            # Note: start_tag and end_tag are regexes
            #start_tag: '[%'
            #end_tag:   '%]'
            start_tag: '\{\{'
            end_tag:   '\}\}'

