# === Basic configuration ===
site:
    url: "https://test.blog"
    appname: "test.blog"
    title: 'Waltz Test Blog'
    paginate: 5
    copyright: "Copyright &copy; Jason A. Crome 2021"
    license: ""
    comment_count: true
    gdpr: false
    locale: "en_US"

author:
    name: 'Jason A. Crome'
    bio: "Perl hacker, Dancer developer, entrepreneur, pilot, hockey player"
    location: "Charlotte, North Carolina, USA"
    email: 'jason@crome-plated.com'

# === Waltz/Dancer specific - don't change unless you know what you're doing! ===
# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer2 will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# Engine config
template: "template_toolkit"
engines:
    template:
        template_toolkit:
            start_tag: '[%'
            end_tag:   '%]'

